/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBibleRouteImport } from './routes/_app.bible'
import { Route as AppLiveRouteImport } from './routes/_app.live'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppOutputsRouteImport } from './routes/_app.outputs'
import { Route as AppPresetsRouteImport } from './routes/_app.presets'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSongsRouteImport } from './routes/_app.songs'
import { Route as OutputMainRouteImport } from './routes/output.main'
import { Route as AppBibleIndexRouteImport } from './routes/_app.bible.index'
import { Route as AppBibleVersionIdRouteImport } from './routes/_app.bible.$versionId'
import { Route as AppPresetsIndexRouteImport } from './routes/_app.presets.index'
import { Route as AppPresetsPresetIdRouteImport } from './routes/_app.presets.$presetId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppSongsIndexRouteImport } from './routes/_app.songs.index'
import { Route as AppSongsSongIdRouteImport } from './routes/_app.songs.$songId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibleRoute = AppBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppOutputsRoute = AppOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AppRoute,
} as any)
const AppPresetsRoute = AppPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSongsRoute = AppSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AppRoute,
} as any)
const OutputMainRoute = OutputMainRouteImport.update({
  id: '/output/main',
  path: '/output/main',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBibleIndexRoute = AppBibleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBibleRoute,
} as any)
const AppBibleVersionIdRoute = AppBibleVersionIdRouteImport.update({
  id: '/$versionId',
  path: '/$versionId',
  getParentRoute: () => AppBibleRoute,
} as any)
const AppPresetsIndexRoute = AppPresetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPresetsRoute,
} as any)
const AppPresetsPresetIdRoute = AppPresetsPresetIdRouteImport.update({
  id: '/$presetId',
  path: '/$presetId',
  getParentRoute: () => AppPresetsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSongsRoute,
} as any)
const AppSongsSongIdRoute = AppSongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => AppSongsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bible': typeof AppBibleRouteWithChildren
  '/live': typeof AppLiveRoute
  '/media': typeof AppMediaRoute
  '/outputs': typeof AppOutputsRoute
  '/presets': typeof AppPresetsRouteWithChildren
  '/projects': typeof AppProjectsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/songs': typeof AppSongsRouteWithChildren
  '/output/main': typeof OutputMainRoute
  '/bible/$versionId': typeof AppBibleVersionIdRoute
  '/presets/$presetId': typeof AppPresetsPresetIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/songs/$songId': typeof AppSongsSongIdRoute
  '/bible/': typeof AppBibleIndexRoute
  '/presets/': typeof AppPresetsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/songs/': typeof AppSongsIndexRoute
}
export interface FileRoutesByTo {
  '/live': typeof AppLiveRoute
  '/media': typeof AppMediaRoute
  '/outputs': typeof AppOutputsRoute
  '/settings': typeof AppSettingsRoute
  '/output/main': typeof OutputMainRoute
  '/': typeof AppIndexRoute
  '/bible/$versionId': typeof AppBibleVersionIdRoute
  '/presets/$presetId': typeof AppPresetsPresetIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/songs/$songId': typeof AppSongsSongIdRoute
  '/bible': typeof AppBibleIndexRoute
  '/presets': typeof AppPresetsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/songs': typeof AppSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/bible': typeof AppBibleRouteWithChildren
  '/_app/live': typeof AppLiveRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/outputs': typeof AppOutputsRoute
  '/_app/presets': typeof AppPresetsRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/songs': typeof AppSongsRouteWithChildren
  '/output/main': typeof OutputMainRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bible/$versionId': typeof AppBibleVersionIdRoute
  '/_app/presets/$presetId': typeof AppPresetsPresetIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/songs/$songId': typeof AppSongsSongIdRoute
  '/_app/bible/': typeof AppBibleIndexRoute
  '/_app/presets/': typeof AppPresetsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/songs/': typeof AppSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/live'
    | '/media'
    | '/outputs'
    | '/presets'
    | '/projects'
    | '/settings'
    | '/songs'
    | '/output/main'
    | '/bible/$versionId'
    | '/presets/$presetId'
    | '/projects/$projectId'
    | '/songs/$songId'
    | '/bible/'
    | '/presets/'
    | '/projects/'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/live'
    | '/media'
    | '/outputs'
    | '/settings'
    | '/output/main'
    | '/'
    | '/bible/$versionId'
    | '/presets/$presetId'
    | '/projects/$projectId'
    | '/songs/$songId'
    | '/bible'
    | '/presets'
    | '/projects'
    | '/songs'
  id:
    | '__root__'
    | '/_app'
    | '/_app/bible'
    | '/_app/live'
    | '/_app/media'
    | '/_app/outputs'
    | '/_app/presets'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/songs'
    | '/output/main'
    | '/_app/'
    | '/_app/bible/$versionId'
    | '/_app/presets/$presetId'
    | '/_app/projects/$projectId'
    | '/_app/songs/$songId'
    | '/_app/bible/'
    | '/_app/presets/'
    | '/_app/projects/'
    | '/_app/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OutputMainRoute: typeof OutputMainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bible': {
      id: '/_app/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof AppBibleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outputs': {
      id: '/_app/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof AppOutputsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/presets': {
      id: '/_app/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AppPresetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/songs': {
      id: '/_app/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof AppSongsRouteImport
      parentRoute: typeof AppRoute
    }
    '/output/main': {
      id: '/output/main'
      path: '/output/main'
      fullPath: '/output/main'
      preLoaderRoute: typeof OutputMainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bible/': {
      id: '/_app/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof AppBibleIndexRouteImport
      parentRoute: typeof AppBibleRoute
    }
    '/_app/bible/$versionId': {
      id: '/_app/bible/$versionId'
      path: '/$versionId'
      fullPath: '/bible/$versionId'
      preLoaderRoute: typeof AppBibleVersionIdRouteImport
      parentRoute: typeof AppBibleRoute
    }
    '/_app/presets/': {
      id: '/_app/presets/'
      path: '/'
      fullPath: '/presets/'
      preLoaderRoute: typeof AppPresetsIndexRouteImport
      parentRoute: typeof AppPresetsRoute
    }
    '/_app/presets/$presetId': {
      id: '/_app/presets/$presetId'
      path: '/$presetId'
      fullPath: '/presets/$presetId'
      preLoaderRoute: typeof AppPresetsPresetIdRouteImport
      parentRoute: typeof AppPresetsRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/songs/': {
      id: '/_app/songs/'
      path: '/'
      fullPath: '/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppSongsRoute
    }
    '/_app/songs/$songId': {
      id: '/_app/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof AppSongsSongIdRouteImport
      parentRoute: typeof AppSongsRoute
    }
  }
}

interface AppBibleRouteChildren {
  AppBibleVersionIdRoute: typeof AppBibleVersionIdRoute
  AppBibleIndexRoute: typeof AppBibleIndexRoute
}

const AppBibleRouteChildren: AppBibleRouteChildren = {
  AppBibleVersionIdRoute: AppBibleVersionIdRoute,
  AppBibleIndexRoute: AppBibleIndexRoute,
}

const AppBibleRouteWithChildren = AppBibleRoute._addFileChildren(
  AppBibleRouteChildren,
)

interface AppPresetsRouteChildren {
  AppPresetsPresetIdRoute: typeof AppPresetsPresetIdRoute
  AppPresetsIndexRoute: typeof AppPresetsIndexRoute
}

const AppPresetsRouteChildren: AppPresetsRouteChildren = {
  AppPresetsPresetIdRoute: AppPresetsPresetIdRoute,
  AppPresetsIndexRoute: AppPresetsIndexRoute,
}

const AppPresetsRouteWithChildren = AppPresetsRoute._addFileChildren(
  AppPresetsRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSongsRouteChildren {
  AppSongsSongIdRoute: typeof AppSongsSongIdRoute
  AppSongsIndexRoute: typeof AppSongsIndexRoute
}

const AppSongsRouteChildren: AppSongsRouteChildren = {
  AppSongsSongIdRoute: AppSongsSongIdRoute,
  AppSongsIndexRoute: AppSongsIndexRoute,
}

const AppSongsRouteWithChildren = AppSongsRoute._addFileChildren(
  AppSongsRouteChildren,
)

interface AppRouteChildren {
  AppBibleRoute: typeof AppBibleRouteWithChildren
  AppLiveRoute: typeof AppLiveRoute
  AppMediaRoute: typeof AppMediaRoute
  AppOutputsRoute: typeof AppOutputsRoute
  AppPresetsRoute: typeof AppPresetsRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSongsRoute: typeof AppSongsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibleRoute: AppBibleRouteWithChildren,
  AppLiveRoute: AppLiveRoute,
  AppMediaRoute: AppMediaRoute,
  AppOutputsRoute: AppOutputsRoute,
  AppPresetsRoute: AppPresetsRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSongsRoute: AppSongsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OutputMainRoute: OutputMainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
